Add `RArrayIter` to avoid `unsafe` usage of `RArray::as_slice`

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,7 +17,7 @@ jobs:
       fail-fast: false
       matrix:
         os: ["ubuntu-latest", "macos-latest"]
-        ruby: ["3.2", "head"]
+        ruby: ["3.1", "3.2", "head"]
     steps:
       - uses: actions/checkout@v3
 
@@ -81,3 +81,30 @@ jobs:
       - name: Tapioca verify example DSL RBIs
         working-directory: example
         run: bin/tapioca dsl --verify
+
+  memcheck:
+    name: Memcheck
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
+        with:
+          ruby-version: "3.2"
+          bundler-cache: true
+          cargo-cache: true
+          cache-version: v2
+
+      - name: Install deps
+        run: |
+          bundle config unset deployment
+          bundle add ruby_memcheck --version '~> 1.3.1' & # avoid usage in Gemfile bc it pulls in nokogiri
+          sudo apt-get install -y valgrind &
+          wait
+          bundle config set deployment true
+      - name: Run "mem:check" task
+        run: |
+          if ! bundle exec rake mem:check; then
+            echo "::error::Valgrind memory check failed"
+            exit 1
+          fi
